// knowledge-readback.ts - Inject distilled cross-project knowledge at session start
//
// Reads MEMORY/KNOWLEDGE/ domain files generated by KnowledgeHarvester.ts.
// Selects domains relevant to the current project based on keyword matching.
// Returns compact knowledge context for LoadContext.hook.ts injection.
//
// Performance: <10ms (reads 2-4 small files). All reads synchronous.
// Output: ~300-700 chars per injected domain, 2-3 domains typical.

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';

// Project path patterns -> relevant knowledge domains
// Populated from config/domains.jsonc at runtime via config-loader (KAI v5.0.0+).
// Until configured, these are empty — the hook injects nothing (safe default).
// Add your own project mappings in config/domains.jsonc projectMapping field.
const EXCLUDED_PROJECTS: string[] = [];

const PROJECT_DOMAIN_MAP: Array<{ pattern: string; domains: string[] }> = [
  // KAI system projects get ai-infrastructure domain
  { pattern: 'kai', domains: ['ai-infrastructure'] },
  // Add your project→domain mappings in config/domains.jsonc
];

// Default for unrecognized projects: no injection (conservative - avoid wasting tokens)
const DEFAULT_DOMAINS: string[] = [];

// Max domains to inject per session (keeps token budget reasonable)
const MAX_DOMAINS = 3;

/**
 * Determine which knowledge domains are relevant for the current project.
 */
function selectDomains(projectDir: string): string[] {
  // Skip personal/non-work projects entirely
  for (const excluded of EXCLUDED_PROJECTS) {
    if (projectDir.includes(excluded)) return [];
  }

  for (const entry of PROJECT_DOMAIN_MAP) {
    if (projectDir.includes(entry.pattern)) {
      return entry.domains.slice(0, MAX_DOMAINS);
    }
  }
  return DEFAULT_DOMAINS;
}

export interface KnowledgeLoadResult {
  content: string | null;
  injectedDomains: string[];
  totalChars: number;
}

/**
 * Load knowledge context for session injection.
 * Returns content string, list of injected domains, and total char count.
 */
export function loadKnowledgeContext(paiDir: string, projectDir: string): KnowledgeLoadResult {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return { content: null, injectedDomains: [], totalChars: 0 };

  const selectedDomains = selectDomains(projectDir);
  const parts: string[] = [];
  const injectedDomains: string[] = [];
  let totalChars = 0;

  for (const domain of selectedDomains) {
    const filePath = join(knowledgeDir, `${domain}.md`);
    if (!existsSync(filePath)) continue;

    try {
      const content = readFileSync(filePath, 'utf-8').trim();
      if (content.length > 0) {
        parts.push(content);
        injectedDomains.push(domain);
        totalChars += content.length;
      }
    } catch {
      // Skip unreadable files silently
    }
  }

  if (parts.length === 0) return { content: null, injectedDomains: [], totalChars: 0 };

  return {
    content: `\n## Domain Knowledge (auto-injected from MEMORY/KNOWLEDGE/)\n\n${parts.join('\n\n---\n\n')}`,
    injectedDomains,
    totalChars,
  };
}

/**
 * Get a list of all available knowledge domains for diagnostics.
 */
export function listKnowledgeDomains(paiDir: string): string[] {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return [];

  return readdirSync(knowledgeDir)
    .filter(f => f.endsWith('.md') && f !== 'INDEX.md')
    .map(f => f.replace('.md', ''));
}
