// knowledge-readback.ts - Inject distilled cross-project knowledge at session start
//
// Reads MEMORY/KNOWLEDGE/ domain files generated by KnowledgeHarvester.ts.
// Selects domains relevant to the current project based on keyword matching.
// Returns compact knowledge context for LoadContext.hook.ts injection.
//
// Performance: <10ms (reads 2-4 small files). All reads synchronous.
// Output: ~300-700 chars per injected domain, 2-3 domains typical.

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';

// Project path patterns -> relevant knowledge domains
// Each entry maps a substring of CLAUDE_PROJECT_DIR to domain file names
// Personal/non-work projects - skip knowledge injection entirely (zero overhead)
// Personal/non-work projects - skip knowledge injection entirely (zero overhead)
// DevenGithub: work-adjacent but meta (knowledge org) - content already in CONTEXT_ROUTING
const EXCLUDED_PROJECTS = [
  'Steadfast',
  'DevenResume',
  'DevenGithub',
  'Startup',
  'GranolaMCP',
  'cli-hidden-commands',
  'Personal-AI-Infrastructure-Review',
];

const PROJECT_DOMAIN_MAP: Array<{ pattern: string; domains: string[] }> = [
  // Firmware/embedded work gets firmware + api + products
  { pattern: 'Learning-Your Company-Repo', domains: ['firmware', 'api-and-services', 'products', 'devops'] },
  { pattern: 'Learning_Your Company_Repo', domains: ['firmware', 'api-and-services', 'products', 'devops'] },
  // WiFi troubleshooter gets products + ui + api
  { pattern: 'WiFi-Troubleshooter', domains: ['products', 'ui', 'api-and-services'] },
  // TR-069/TR-369 gets api + products
  { pattern: 'TR-069', domains: ['api-and-services', 'products', 'firmware'] },
  { pattern: 'TR_069', domains: ['api-and-services', 'products', 'firmware'] },
  // PAI config gets ai-infrastructure
  { pattern: 'pai-config', domains: ['ai-infrastructure'] },
  { pattern: 'pai_config', domains: ['ai-infrastructure'] },
  // PAI development projects get ai-infrastructure
  { pattern: 'PAI-Continued-Development', domains: ['ai-infrastructure'] },
  { pattern: 'PAI-v4', domains: ['ai-infrastructure'] },
  // Research-Agent: OpenWRT agents + device access tooling + TR-181 assessment
  { pattern: 'Research-Agent', domains: ['firmware', 'api-and-services', 'products'] },
  { pattern: 'Research_Agent', domains: ['firmware', 'api-and-services', 'products'] },
  // AIrouter gets ai-infrastructure
  { pattern: 'AIrouter', domains: ['ai-infrastructure'] },
  // PrivacyGUI gets ui + products
  { pattern: 'PrivacyGUI', domains: ['ui', 'products', 'api-and-services'] },
  // Firmware Inspector gets firmware + products
  { pattern: 'Firmware-Inspector', domains: ['firmware', 'products'] },
  // Release notes gets products + firmware
  { pattern: 'release-notes', domains: ['products', 'firmware'] },
  // Knowledge base gets firmware + products
  { pattern: 'Knowledge', domains: ['firmware', 'products', 'api-and-services'] },
];

// Default for unrecognized projects: no injection (conservative - avoid wasting tokens)
const DEFAULT_DOMAINS: string[] = [];

// Max domains to inject per session (keeps token budget reasonable)
const MAX_DOMAINS = 3;

/**
 * Determine which knowledge domains are relevant for the current project.
 */
function selectDomains(projectDir: string): string[] {
  // Skip personal/non-work projects entirely
  for (const excluded of EXCLUDED_PROJECTS) {
    if (projectDir.includes(excluded)) return [];
  }

  for (const entry of PROJECT_DOMAIN_MAP) {
    if (projectDir.includes(entry.pattern)) {
      return entry.domains.slice(0, MAX_DOMAINS);
    }
  }
  return DEFAULT_DOMAINS;
}

/**
 * Load knowledge context for session injection.
 * Returns a formatted string with relevant domain knowledge, or null if none available.
 */
export function loadKnowledgeContext(paiDir: string, projectDir: string): string | null {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return null;

  const selectedDomains = selectDomains(projectDir);
  const parts: string[] = [];

  for (const domain of selectedDomains) {
    const filePath = join(knowledgeDir, `${domain}.md`);
    if (!existsSync(filePath)) continue;

    try {
      const content = readFileSync(filePath, 'utf-8').trim();
      if (content.length > 0) {
        parts.push(content);
      }
    } catch {
      // Skip unreadable files silently
    }
  }

  if (parts.length === 0) return null;

  return `\n## Domain Knowledge (auto-injected from MEMORY/KNOWLEDGE/)\n\n${parts.join('\n\n---\n\n')}`;
}

/**
 * Get a list of all available knowledge domains for diagnostics.
 */
export function listKnowledgeDomains(paiDir: string): string[] {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return [];

  return readdirSync(knowledgeDir)
    .filter(f => f.endsWith('.md') && f !== 'INDEX.md')
    .map(f => f.replace('.md', ''));
}
