// knowledge-readback.ts - Inject distilled cross-project knowledge at session start
//
// Reads MEMORY/KNOWLEDGE/ domain files generated by KnowledgeHarvester.ts.
// Selects domains relevant to the current project based on keyword matching.
// Returns compact knowledge context for LoadContext.hook.ts injection.
//
// Performance: <10ms (reads 2-4 small files). All reads synchronous.
// Output: ~300-700 chars per injected domain, 2-3 domains typical.

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';
import { loadProjectMapping, loadExcludedProjects, getMaxDomainsPerSession } from './config-loader';

/**
 * Determine which knowledge domains are relevant for the current project.
 * Reads mappings from config/domains.jsonc via config-loader.
 */
function selectDomains(projectDir: string): string[] {
  const excluded = loadExcludedProjects();
  const mapping = loadProjectMapping();
  const maxDomains = getMaxDomainsPerSession();

  for (const pattern of excluded) {
    if (projectDir.includes(pattern)) return [];
  }

  for (const entry of mapping) {
    if (projectDir.includes(entry.pattern)) {
      return entry.domains.slice(0, maxDomains);
    }
  }
  return [];
}

export interface KnowledgeLoadResult {
  content: string | null;
  injectedDomains: string[];
  totalChars: number;
}

/**
 * Load knowledge context for session injection.
 * Returns content string, list of injected domains, and total char count.
 */
export function loadKnowledgeContext(paiDir: string, projectDir: string): KnowledgeLoadResult {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return { content: null, injectedDomains: [], totalChars: 0 };

  const selectedDomains = selectDomains(projectDir);
  const parts: string[] = [];
  const injectedDomains: string[] = [];
  let totalChars = 0;

  for (const domain of selectedDomains) {
    const filePath = join(knowledgeDir, `${domain}.md`);
    if (!existsSync(filePath)) continue;

    try {
      const content = readFileSync(filePath, 'utf-8').trim();
      if (content.length > 0) {
        parts.push(content);
        injectedDomains.push(domain);
        totalChars += content.length;
      }
    } catch {
      // Skip unreadable files silently
    }
  }

  if (parts.length === 0) return { content: null, injectedDomains: [], totalChars: 0 };

  return {
    content: `\n## Domain Knowledge (auto-injected from MEMORY/KNOWLEDGE/)\n\n${parts.join('\n\n---\n\n')}`,
    injectedDomains,
    totalChars,
  };
}

/**
 * Get a list of all available knowledge domains for diagnostics.
 */
export function listKnowledgeDomains(paiDir: string): string[] {
  const knowledgeDir = join(paiDir, 'MEMORY', 'KNOWLEDGE');
  if (!existsSync(knowledgeDir)) return [];

  return readdirSync(knowledgeDir)
    .filter(f => f.endsWith('.md') && f !== 'INDEX.md')
    .map(f => f.replace('.md', ''));
}
