// staging.ts - Draft memory staging area management
//
// Manages MEMORY/STAGING/ directory for draft memories awaiting review.
// Drafts are generated by rating-triggered hooks and reviewed via `pai curate`.
// All drafts expire after 14 days if not approved.
//
// Used by: RatingCapture.hook.ts (write), MemoryCurate.ts (read/approve/reject)

import { readFileSync, writeFileSync, existsSync, readdirSync, unlinkSync, mkdirSync } from 'fs';
import { join } from 'path';
import { paiPath } from './paths';

const STAGING_DIR = paiPath('MEMORY', 'STAGING');
const STATE_FILE = join(STAGING_DIR, '.staging-state.json');
const EXPIRY_DAYS = 14;

export interface DraftMemory {
  filename: string;
  type: 'success-pattern' | 'correction' | 'pattern-insight';
  sourceSession: string;
  sourceRating?: number;
  confidence: number;
  generated: string; // ISO timestamp
  expires: string;   // ISO timestamp
  targetProject: string;
  targetFilename: string;
  title: string;
  content: string;
}

interface StagingState {
  created: string;
  expiryDays: number;
  drafts: Array<{
    filename: string;
    generated: string;
    expires: string;
    type: string;
  }>;
  stats: {
    totalGenerated: number;
    totalApproved: number;
    totalRejected: number;
    totalExpired: number;
  };
}

function loadState(): StagingState {
  if (!existsSync(STATE_FILE)) {
    return {
      created: new Date().toISOString().split('T')[0],
      expiryDays: EXPIRY_DAYS,
      drafts: [],
      stats: { totalGenerated: 0, totalApproved: 0, totalRejected: 0, totalExpired: 0 },
    };
  }
  try {
    return JSON.parse(readFileSync(STATE_FILE, 'utf-8'));
  } catch {
    return {
      created: new Date().toISOString().split('T')[0],
      expiryDays: EXPIRY_DAYS,
      drafts: [],
      stats: { totalGenerated: 0, totalApproved: 0, totalRejected: 0, totalExpired: 0 },
    };
  }
}

function saveState(state: StagingState): void {
  mkdirSync(STAGING_DIR, { recursive: true });
  writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

/**
 * Write a draft memory to the staging area.
 */
export function writeDraft(draft: Omit<DraftMemory, 'filename' | 'expires'>): string {
  mkdirSync(STAGING_DIR, { recursive: true });

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const slug = draft.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
  const filename = `${timestamp}_${draft.type}_${slug}.md`;

  const expires = new Date(Date.now() + EXPIRY_DAYS * 24 * 60 * 60 * 1000).toISOString();

  const fileContent = `---
type: draft-memory
source_type: ${draft.type}
source_session: ${draft.sourceSession}
source_rating: ${draft.sourceRating ?? 'n/a'}
confidence: ${draft.confidence}
generated: ${draft.generated}
expires: ${expires}
target_project: ${draft.targetProject}
target_filename: ${draft.targetFilename}
title: "${draft.title}"
---

${draft.content}
`;

  writeFileSync(join(STAGING_DIR, filename), fileContent);

  // Update state
  const state = loadState();
  state.drafts.push({ filename, generated: draft.generated, expires, type: draft.type });
  state.stats.totalGenerated++;
  saveState(state);

  return filename;
}

/**
 * List all pending draft memories (excluding expired).
 */
export function listDrafts(): DraftMemory[] {
  if (!existsSync(STAGING_DIR)) return [];

  const files = readdirSync(STAGING_DIR).filter(f => f.endsWith('.md'));
  const drafts: DraftMemory[] = [];
  const now = Date.now();

  for (const file of files) {
    try {
      const content = readFileSync(join(STAGING_DIR, file), 'utf-8');
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
      if (!frontmatterMatch) continue;

      const fm = frontmatterMatch[1];
      const body = frontmatterMatch[2].trim();

      const get = (key: string): string => {
        const m = fm.match(new RegExp(`^${key}:\\s*"?(.+?)"?\\s*$`, 'm'));
        return m?.[1] ?? '';
      };

      const expires = get('expires');
      if (expires && new Date(expires).getTime() < now) continue; // expired

      drafts.push({
        filename: file,
        type: get('source_type') as DraftMemory['type'],
        sourceSession: get('source_session'),
        sourceRating: parseFloat(get('source_rating')) || undefined,
        confidence: parseFloat(get('confidence')) || 0,
        generated: get('generated'),
        expires,
        targetProject: get('target_project'),
        targetFilename: get('target_filename'),
        title: get('title'),
        content: body,
      });
    } catch { /* skip malformed */ }
  }

  return drafts.sort((a, b) => b.confidence - a.confidence);
}

/**
 * Remove expired drafts. Returns count of expired files removed.
 */
export function cleanupExpired(): number {
  if (!existsSync(STAGING_DIR)) return 0;

  const files = readdirSync(STAGING_DIR).filter(f => f.endsWith('.md'));
  const now = Date.now();
  let removed = 0;

  for (const file of files) {
    try {
      const content = readFileSync(join(STAGING_DIR, file), 'utf-8');
      const expiresMatch = content.match(/^expires:\s*(.+)$/m);
      if (expiresMatch) {
        const expires = new Date(expiresMatch[1].trim()).getTime();
        if (expires < now) {
          unlinkSync(join(STAGING_DIR, file));
          removed++;
        }
      }
    } catch { /* skip */ }
  }

  if (removed > 0) {
    const state = loadState();
    state.stats.totalExpired += removed;
    state.drafts = state.drafts.filter(d => {
      return !d.expires || new Date(d.expires).getTime() >= now;
    });
    saveState(state);
  }

  return removed;
}

/**
 * Approve a draft: move from STAGING to target project memory.
 */
export function approveDraft(filename: string): { success: boolean; targetPath?: string; error?: string } {
  const filePath = join(STAGING_DIR, filename);
  if (!existsSync(filePath)) return { success: false, error: 'Draft not found' };

  const drafts = listDrafts();
  const draft = drafts.find(d => d.filename === filename);
  if (!draft) return { success: false, error: 'Draft expired or malformed' };

  // The target path is stored in the draft frontmatter
  // Approval logic will be implemented in MemoryCurate.ts which handles
  // moving the file, updating MEMORY.md index, etc.
  // For now, just update the state.
  const state = loadState();
  state.stats.totalApproved++;
  state.drafts = state.drafts.filter(d => d.filename !== filename);
  saveState(state);

  // Remove from staging
  unlinkSync(filePath);

  return { success: true, targetPath: draft.targetFilename };
}

/**
 * Reject a draft: remove from STAGING and log rejection.
 */
export function rejectDraft(filename: string, reason?: string): boolean {
  const filePath = join(STAGING_DIR, filename);
  if (!existsSync(filePath)) return false;

  // Log rejection for confidence calibration
  try {
    const rejectLog = join(STAGING_DIR, '.rejections.jsonl');
    const entry = {
      timestamp: new Date().toISOString(),
      filename,
      reason: reason || 'no reason given',
    };
    const { appendFileSync: append } = require('fs');
    append(rejectLog, JSON.stringify(entry) + '\n');
  } catch { /* non-critical */ }

  // Remove from staging
  unlinkSync(filePath);

  // Update state
  const state = loadState();
  state.stats.totalRejected++;
  state.drafts = state.drafts.filter(d => d.filename !== filename);
  saveState(state);

  return true;
}
