#!/usr/bin/env bun
/**
 * GenerateManifest.ts — Generate manifest.json for a PAI release
 *
 * Computes SHA-256 checksums for all PAI system files (excluding user data).
 * Run this script when creating a new release to update manifest.json.
 *
 * Usage:
 *   bun ~/.claude/PAI/Tools/GenerateManifest.ts
 *   bun ~/.claude/PAI/Tools/GenerateManifest.ts --source /path/to/.claude
 *   bun ~/.claude/PAI/Tools/GenerateManifest.ts --out /path/to/manifest.json
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'fs';
import { join, relative } from 'path';
import { homedir } from 'os';
import { atomicWriteJSON } from '../../hooks/lib/atomic.ts';
import type { Manifest, ManifestEntry } from './upgrade.ts';

// ── Paths excluded from manifest (user data, runtime state, generated files) ──

const EXCLUDE_PATHS = new Set([
  'MEMORY',
  'PAI/USER',
  'MCPs',
  '.mcp.json',
  'projects',
  'settings.json',        // generated by BuildSettings.ts
  'CLAUDE.md',            // generated by BuildCLAUDE.ts
  'node_modules',
  '.git',
  'bun.lock',
  'bun.lockb',
]);

/** Extensions to exclude (binary, large data files) */
const EXCLUDE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.gif', '.mp3', '.mp4', '.wav']);

// ── Walk and filter ───────────────────────────────────────────────────────

function shouldExclude(relPath: string): boolean {
  // Check excluded path prefixes
  for (const excluded of EXCLUDE_PATHS) {
    if (relPath === excluded || relPath.startsWith(excluded + '/')) return true;
  }
  // Check extension
  const ext = relPath.slice(relPath.lastIndexOf('.')).toLowerCase();
  if (EXCLUDE_EXTENSIONS.has(ext)) return true;
  return false;
}

function walkFiles(dir: string, baseDir: string): ManifestEntry[] {
  const entries: ManifestEntry[] = [];

  if (!existsSync(dir)) return entries;

  for (const name of readdirSync(dir)) {
    const fullPath = join(dir, name);
    const relPath = relative(baseDir, fullPath);

    if (shouldExclude(relPath) || shouldExclude(name)) continue;

    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      entries.push(...walkFiles(fullPath, baseDir));
    } else {
      const content = readFileSync(fullPath);
      const hasher = new Bun.CryptoHasher('sha256');
      hasher.update(content);
      entries.push({
        path: relPath,
        sha256: hasher.digest('hex'),
        size: stat.size,
      });
    }
  }

  return entries;
}

// ── Main ──────────────────────────────────────────────────────────────────

function getBunVersion(): string {
  const result = Bun.spawnSync(['bun', '--version']);
  return result.stdout.toString().trim();
}

function getPAIVersion(paiDir: string): string {
  const settingsPath = join(paiDir, 'settings.json');
  if (!existsSync(settingsPath)) return 'unknown';
  try {
    const s = JSON.parse(readFileSync(settingsPath, 'utf-8')) as Record<string, unknown>;
    const pai = s.pai as Record<string, unknown> | undefined;
    return typeof pai?.version === 'string' ? pai.version : 'unknown';
  } catch {
    return 'unknown';
  }
}

if (import.meta.main) {
  const args = process.argv.slice(2);

  let sourceDir = process.env.PAI_DIR ?? join(homedir(), '.claude');
  let outPath: string | undefined;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--source' && args[i + 1]) sourceDir = args[++i];
    if (args[i] === '--out' && args[i + 1]) outPath = args[++i];
  }

  if (!existsSync(sourceDir)) {
    console.error(`Source directory not found: ${sourceDir}`);
    process.exit(1);
  }

  outPath = outPath ?? join(sourceDir, 'manifest.json');

  console.log(`Scanning: ${sourceDir}`);
  const files = walkFiles(sourceDir, sourceDir);
  files.sort((a, b) => a.path.localeCompare(b.path));

  const manifest: Manifest = {
    version: getPAIVersion(sourceDir),
    generatedAt: new Date().toISOString(),
    bunMinVersion: getBunVersion(),
    files,
  };

  atomicWriteJSON(outPath, manifest);
  console.log(`✓ manifest.json written: ${files.length} files → ${outPath}`);
}
